$(document).on('ready',function(){
    $(".full-screen").slick({
        centerMode:true,
        centerPadding:'5%',
        dots:true,
        autoplay:true,
        autoplaySpeed:3000,
        speed:1000,
        infinite:true,
    });
});